CREATE TABLE [dbo].[DataTypes] (
    [DataTypeId] UNIQUEIDENTIFIER NOT NULL,
    [Type]       NVARCHAR (255)   NOT NULL,
    CONSTRAINT [PK_DataTypeId] PRIMARY KEY CLUSTERED ([DataTypeId]),
    CONSTRAINT [UC_DataTypes_Name] UNIQUE NONCLUSTERED ([Type] ASC)
);

